version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB-Test
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      
volumes:
  data:
